spring.application.name=Bicho-full-Jogo-Educacional
spring.datasource.url=jdbc:mysql://localhost:3306/bicho_db
spring.datasource.username=J_ivan_user
spring.datasource.password=Eng.Soft.2023-2027
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
api.security.token.secret=my-secret-key-bichofull
